// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoIntegrador.Backend.Dados;

#nullable disable

namespace ProjetoIntegrador.Backend.Migrations
{
    [DbContext(typeof(AppDbContexto))]
    [Migration("20260826202812_RemoveEmailTelefoneUnicoContato")]
    partial class RemoveEmailTelefoneUnicoContato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraDisparo")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("PrecisaoGps")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Vinculo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Telefone");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Passos")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("TagRestricao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TempoPreparoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.ReceitaFavorita", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId", "ReceitaId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitasFavoritas");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Alerta", b =>
                {
                    b.HasOne("ProjetoIntegrador.Backend.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Contato", b =>
                {
                    b.HasOne("ProjetoIntegrador.Backend.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Receita", b =>
                {
                    b.OwnsOne("ProjetoIntegrador.Backend.Modelos.MacrosNutricionais", "Macros", b1 =>
                        {
                            b1.Property<int>("ReceitaId")
                                .HasColumnType("int");

                            b1.Property<int>("CarboidratosPorcentagem")
                                .HasColumnType("int")
                                .HasColumnName("CarboidratosPorcentagem");

                            b1.Property<int>("GordurasPorcentagem")
                                .HasColumnType("int")
                                .HasColumnName("GordurasPorcentagem");

                            b1.Property<int>("ProteinaPorcentagem")
                                .HasColumnType("int")
                                .HasColumnName("ProteinaPorcentagem");

                            b1.HasKey("ReceitaId");

                            b1.ToTable("Receitas");

                            b1.WithOwner()
                                .HasForeignKey("ReceitaId");
                        });

                    b.Navigation("Macros")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.ReceitaFavorita", b =>
                {
                    b.HasOne("ProjetoIntegrador.Backend.Modelos.Receita", "Receita")
                        .WithMany("FavoritadoPor")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoIntegrador.Backend.Modelos.Usuario", "Usuario")
                        .WithMany("ReceitasFavoritas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Receita", b =>
                {
                    b.Navigation("FavoritadoPor");
                });

            modelBuilder.Entity("ProjetoIntegrador.Backend.Modelos.Usuario", b =>
                {
                    b.Navigation("ReceitasFavoritas");
                });
#pragma warning restore 612, 618
        }
    }
}
